### ISSUE TITLE
Add To Cart fails with 400: Bad Request

### ISSUE THREAD

**Issue by PolGuixe** [parmsang/gatsby-starter-ecommerce#19]
After cloning, adding my details - MOLTIN_CLIENT_ID, ... -, and cleaning-up the graphql queries for the site to compile properly. When I am trying to add a product to the cart I am getting a 400 error from the Moltin API. 

Any idea?

**Comment by amponce** [comment]
I ran into the same issue, partly because I renamed the `MOLTIN_CLIENT_ID` to `GATSBY_MOLTIN_CLIENT_ID` in `gatsby-config` and didn't realize there was another reference in `lib/moltin.js` so make sure that matches. 

My theory is either your .env isn't set up correctly or you hardcoded the ID like so:

```
File: gatsby-config.js
process.env.GATSBY_MOLTIN_CLIENT_ID || 'kdkdkksldkflmsdkfjdsjfksdjfkljdsafjd',

File: /lib/miltin.js  
process.env.GATSBY_MOLTIN_CLIENT_ID || 'kdkdkksldkflmsdkfjdsjfksdjfkljdsafjd',

```

Maybe doublecheck that the npm dotenv package is installed in your **devDependencies**.

I'm using  Netlify to add the production environment variables via the deploy settings, so I decided not to use more than one `.env`

 ```
File: gatsby-config.js

require('dotenv').config()

File: .env

GATSBY_MOLTIN_CLIENT_ID=#######
STRIPE_PUBLISHABLE_KEY=pk_test_####
```
Once you get your .env working you should be able to get away with just:
```
File: gatsby-config.js

process.env.GATSBY_MOLTIN_CLIENT_ID || '',

File: /lib/miltin.js  

process.env.GATSBY_MOLTIN_CLIENT_ID || '',
```

**Comment by parmsang** [comment]
I have updated the code. Do you still have any problems?

**Comment by parmsang** [comment]
I'm closing this as there has been no update from original author.
Note that code has been updated.
